version: '3.8'
services:
  graphql-engine:
      image: hasura/graphql-engine:v2.2.0
      ports:
      - "8080:8080"
      expose:
        - "8080"
      env_file:
        - .env
      restart: always
      environment:
        ## postgres database to store Hasura metadata
        HASURA_GRAPHQL_METADATA_DATABASE_URL: "postgresql://prisma:topsecret@postgres:5432/blog"
        ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
        PG_DATABASE_URL: "postgresql://prisma:topsecret@postgres:5432/blog"
        ## enable the console served by server
        HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
        ## enable debugging mode. It is recommended to disable this in production
        HASURA_GRAPHQL_DEV_MODE: "true"
        HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
        ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
        # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
        ## uncomment next line to set an admin secret
        # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
