version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - graphql-engine
    links:
      - postgres
      - graphql-engine
    env_file:
      - .env

  graphql-engine:
      image: hasura/graphql-engine
      ports:
      - "8080:8080"
      expose:
        - "8080"
      env_file:
        - .env
      restart: always
      depends_on:
        - postgres
      environment:
        ## postgres database to store Hasura metadata
        HASURA_GRAPHQL_METADATA_DATABASE_URL: "postgresql://prisma:topsecret@postgres:5432/postgres"
        ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
        PG_DATABASE_URL: "postgresql://prisma:topsecret@postgres:5432/postgres"
        NEST_API_URL: "http://nest-api:3000/graphql"
        NESTJS_EVENT_WEBHOOK_ENDPOINT: "http://nest-api:3000/hasura/events"
        HASURA_NESTJS_WEBHOOK_SECRET_HEADER_VALUE: "topsecret"
        ## enable the console served by server
        HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
        ## enable debugging mode. It is recommended to disable this in production
        HASURA_GRAPHQL_DEV_MODE: "true"
        HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
        ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
        # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
        ## uncomment next line to set an admin secret
        # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
        HASURA_GRAPHQL_ENDPOINT: http://127.0.0.1:8080

  n8n:
    image: n8nio/n8n
    environment:
      - N8N_ENCRYPTION_KEY=68566D597133743677397A244226452948404D635166546A576E5A7234753778
      - EXECUTIONS_MODE=regular
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - N8N_HOST=0.0.0.0
      - N8N_PORT=8081
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_USER=prisma
      - DB_POSTGRESDB_PASSWORD=topsecret
      # - WEBHOOK_URL=https://n8n.app.flowgical.io/
      # - N8N_EDITOR_BASE_URL=https://n8n.app.flowgical.io/
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
    command: /bin/sh -c "n8n start"
    ports:
      - 8081:8081
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  

volumes:
  postgres:
    name: nest-db
