import { registerEnumType } from '@nestjs/graphql';

export enum TaskScalarFieldEnum {
    id = "id",
    title = "title",
    description = "description",
    dueDate = "dueDate",
    priority = "priority",
    isActive = "isActive",
    key = "key",
    properties = "properties",
    values = "values",
    type = "type",
    typeName = "typeName",
    cta = "cta",
    ctaName = "ctaName",
    state = "state",
    stateName = "stateName",
    status = "status",
    statusName = "statusName",
    stateValues = "stateValues",
    descriptionTemplate = "descriptionTemplate",
    titleTemplate = "titleTemplate",
    statusTemplate = "statusTemplate",
    stateTemplate = "stateTemplate",
    notificationTemplate = "notificationTemplate",
    ctaTemplate = "ctaTemplate",
    machineConfig = "machineConfig",
    contextConfig = "contextConfig",
    stateConfig = "stateConfig",
    statusConfig = "statusConfig",
    notificationConfig = "notificationConfig",
    processConfig = "processConfig",
    triggerConfig = "triggerConfig",
    ctaConfig = "ctaConfig",
    formConfig = "formConfig",
    config = "config",
    createdAt = "createdAt",
    updatedAt = "updatedAt",
    definitionId = "definitionId",
    formId = "formId",
    projectId = "projectId",
    assigneeId = "assigneeId",
    creatorId = "creatorId",
    parentId = "parentId",
    organizationId = "organizationId",
    reporterId = "reporterId",
    teamId = "teamId"
}


registerEnumType(TaskScalarFieldEnum, { name: 'TaskScalarFieldEnum', description: undefined })
