table:
  name: Task
  schema: public
object_relationships:
  - name: Form
    using:
      foreign_key_constraint_on: formId
  - name: Organization
    using:
      foreign_key_constraint_on: organizationId
  - name: Project
    using:
      foreign_key_constraint_on: projectId
  - name: Task
    using:
      foreign_key_constraint_on: parentId
  - name: TaskDefinition
    using:
      foreign_key_constraint_on: definitionId
  - name: Team
    using:
      foreign_key_constraint_on: teamId
  - name: User
    using:
      foreign_key_constraint_on: assigneeId
  - name: userByCreatorid
    using:
      foreign_key_constraint_on: creatorId
  - name: userByReporterid
    using:
      foreign_key_constraint_on: reporterId
array_relationships:
  - name: Comments
    using:
      foreign_key_constraint_on:
        column: taskId
        table:
          name: Comment
          schema: public
  - name: EventLogs
    using:
      foreign_key_constraint_on:
        column: taskId
        table:
          name: EventLog
          schema: public
  - name: Tasks
    using:
      foreign_key_constraint_on:
        column: parentId
        table:
          name: Task
          schema: public
  - name: Triggers
    using:
      foreign_key_constraint_on:
        column: taskId
        table:
          name: Trigger
          schema: public
event_triggers:
  - name: task-created
    definition:
      enable_manual: true
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 15
      num_retries: 3
      timeout_sec: 100
    webhook_from_env: NESTJS_EVENT_WEBHOOK_ENDPOINT
    headers:
      - name: x-hasura-secret
        value_from_env: HASURA_NESTJS_WEBHOOK_SECRET_HEADER_VALUE
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
